modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Slexom/animal-feeding-trough/issues"
license = "MIT"

[[mods]]
modId = "animal_feeding_trough"
version = "${version}"
displayName = "Animal Feeding Trough"
authors = "Slexom"
description = '''
-
'''
logoFile = "icon.png"

[[dependencies.animal_feeding_trough]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.8,)"
ordering = "AFTER"
side = "BOTH"